# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   dwr_global_weather_configuration:
      wsdl: http://www.webservicex.net/globalweather.asmx?WSDL
      timeout: 10
   dwr_global_weather_locations:
      Poland: [Katowice, Krakow]
      Germany: [Berlin]

services:
    dwr_global_weather_client:
        class: Dwr\GlobalWeatherBundle\WeatherService\Client\GlobalWeatherClient
        arguments: ["%dwr_global_weather_configuration%"]

    dwr_global_weather:
        class: Dwr\GlobalWeatherBundle\WeatherService\GlobalWeather
        arguments: ["@dwr_global_weather_client"]
