# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   dwr_global_weather_configuration:
      wsdl: http://www.webservicex.net/globalweather.asmx?WSDL
      timeout: 10
   dwr_global_weather_locations:
      Australia: [Sydney Airport]
      Germany: [Berlin]
      Japan: [Tokyo]
      Poland: [Katowice, Krakow, Warszawa-Okecie]
      Russian Federation: [Moscow]
      Spain: [Barcelona, Fuerteventura, Las Palmas De Gran Canaria / Gando]
      United States: [New York]

services:
    dwr_global_weather_client:
        class: Dwr\GlobalWeatherBundle\WeatherService\Client\GlobalWeatherClient
        arguments: ["%dwr_global_weather_configuration%"]

    dwr_global_weather_parserXML:
        class: Dwr\GlobalWeatherBundle\Utility\ParserXML

    dwr_global_weather:
        class: Dwr\GlobalWeatherBundle\WeatherService\GlobalWeather
        arguments: ["@dwr_global_weather_client", "@dwr_global_weather_parserXML"]

    dwr_global_weather_location_choice:
        class: Dwr\GlobalWeatherBundle\Form\LocationChoice
        arguments: ["%dwr_global_weather_locations%"]

    dwr_global_weather_form_type:
        class: Dwr\GlobalWeatherBundle\Form\Type\GlobalWeatherType
        arguments: ["@dwr_global_weather_location_choice"]
